### ISSUE TITLE
Line no 44 error

### ISSUE THREAD

**Issue by Akshay-Hegde** [heyman/leaflet-areaselect#10]
this._container.remove is not a function

this._container.remove();

I am just creating button like this
var areaSelect , toggle = true;
$("#button").on("click",function(){
if(toggle)
{
 areaSelect = L.areaSelect().addTo(map)
}else{
  areaSelect.remove();
}
toggle = !toggle;
})

Let me know if am wrong.

**Comment by iH8** [comment]
@heyman encountered this bug on SO, see: http://stackoverflow.com/questions/28465382/leaflet-areaselect-remove-on-internet-explorer/

**Comment by heyman** [comment]
@IH8: Thanks a lot for the digging!

**Comment by iH8** [comment]
@heyman, no problem, glad to help out. Good luck with the project
