### ISSUE TITLE
Invalid BBOX coordinates

### ISSUE THREAD

**Issue by blazs** [heyman/leaflet-areaselect#18]
When using Google Chrome, I sometimes getinvalid BBOX coordinates. The bug seems to occur rather sporadically, however, it seems to come up when one zooms in without touching the polygon and then asks for the coordinates (e.g. invokes `getBounds()`).

**Comment by valerio-bozzolan** [comment]
I think your map sometime has zero height or width sometime. Be sure to first initialize the map with an initial position and with a defined height and width before trying to call `map.getBounds()`. You are able to debug it calling `map.getSize()` and checking your browser console.

This is very difficult to reproduce without more information. If you have already fixed or if it's impossible to share further information to reproduce feel free to mark as closed. Thank you so much! :)
