### ISSUE TITLE
areaselect displayed below tile layer

### ISSUE THREAD

**Issue by mrunde** [heyman/leaflet-areaselect#19]
When I add the areaselect plugin to the map, the rectangle will be displayed below the tile layer. I haven't set any `zIndex` for the layer and just followed the example given [here][1]. Has somebody else faced this problem, too? Maybe this is related to issue #12. However, I have this problem with Firefox 45.4.0 and IE 11.

This is my code:

    // Set up the map
    var center = new L.LatLng(52, 10);
    var map = L.map('map').setView(center, 13);
    // Add the tile layer
    L.tileLayer(urlToTileLayer).addTo(map);
    // Add the area select overlay
    var areaSelectOptions = {
        width: 200,
        height: 300
    };
    var areaSelect = L.areaSelect(areaSelectOptions);
    areaSelect.addTo(map);

  [1]:https://github.com/heyman/leaflet-areaselect/blob/master/example/index.html

**Comment by heyman** [comment]
Do you get the same error in the example page (http://heyman.github.io/leaflet-areaselect/example/)?

**Comment by mrunde** [comment]
No, there it works fine. I couldn't find any mistake in my code which could lead to this misbehaviour. Is it possible to add a `zIndex` maybe to the areaSelect overlay?

**Comment by heyman** [comment]
Hmm, what version of Leaflet are you using? I wonder if there's been change that causes this.

Does it work if you add z-index? Or perhaps just `position: relative;`? You can style the container by using the CSS selector `.leaflet-areaselect-container`.

**Comment by mrunde** [comment]
I am using Leaflet version 1.0.2+4bbb16c. I tried out @bdon's solution from #12 but that didn't solve the problem.

**Comment by heyman** [comment]
Ok. Unfortunately I don't have time to debug it, but if you find a solution/reason, please post it here.

**Comment by masterwendu** [comment]
Hello,

I had the same issue,  I forgot to include the css file, then it works.
Maybe this helps you :)

BR

**Comment by mrunde** [comment]
No, the CSS file was included, but thank you anyway. I will close this issue though as I use another plugin and no others seem to have this problem.
