### ISSUE TITLE
npm : package.json

### ISSUE THREAD

**Issue by dawadam** [heyman/leaflet-areaselect#22]
Please add package.json support for npm.

**Comment by daczczcz1** [comment]
I started working on this.

@heyman please let me know if you'd be willing to review my work. I've forked the repo, but it would be probably better to keep it here, since this is officially linked on Leaflet site.

**Comment by lweller** [comment]
@heyman: Hopefully you will be able to integrate my littles fixes in a newa future and be able to release a version. In the meean time I just published a scoped version (1.2.1) to npmjs.org: https://www.npmjs.com/package/@lweller/leaflet-areaselect
