### ISSUE TITLE
New feature with "getDimensions" Function

### ISSUE THREAD

**Issue by hijiangtao** [heyman/leaflet-areaselect#24]
It's really helpful to find the plugin of leaflet when I do my research project recent times, thanks for your efforts of previous developing works. An extra demand came to my mind when I need to handle multiple map instances in an synchronized way, and I add one function to solve my little problem.

The demand shows here: I need to synchronize the different maps when I zoom in/out or pan anyone among of them, as well as synchronize the `areaselect` area, a simple way is to exposed the dimensions of the operating box when the areaselect area detects change and then my other function can set the dimensions of box in other maps with the gotten dimension data, but there is not `getDimensions` function yet, so I added it, shows in #23 .

I also updated README with the usage.

Best.

**Comment by heyman** [comment]
There's now a `getDimensions()` method. Thanks!
