### ISSUE TITLE
Overlapped or not fully covered shade in the interface

### ISSUE THREAD

**Issue by hijiangtao** [heyman/leaflet-areaselect#25]
Hi, I would like to point out one question about the shades' display effect. I initialize the areselect with default parameters but the result shows that the different shades didn't connect perfectly with each other (the white line in the left part of the picture), then I found you use `Math.round` function to deal with the shade's width and height in `_render` function in the code, so isn't any potential problem to cause white line appeared in the initialization process? I also found the white line would disappeared occasionally, but can't control its' appearance during my scaling operations.

Best.

![image](https://cloud.githubusercontent.com/assets/4990015/24202372/ccb62ecc-0f4d-11e7-9a52-55ece4dd5272.png)

**Comment by hijiangtao** [comment]
* The operating system: Ubuntu 16.04 LTS
* Browser: Chrome Version 56.0.2924.87 (64-bit)

**Comment by heyman** [comment]
Hi!

I can't reproduce this in Chrome (56.0.2924.87) on OSX, but it clearly seems to be some kind of issue. I currently don't have any time to look into this. If anyone else find out more, a pull request or more info would be much appreciated!

**Comment by hijiangtao** [comment]
Ok then, thanks for replying.

I would like to give more details about the issue, but I am not sure the information I provided can help you to locate the potential problem.

The fact is that when I used the [official example](http://heyman.github.io/leaflet-areaselect/example/), the same problem appeared again, like the screenshot shows below.

![Uploading FireShot Capture 237 -  - http___heyman.github.io_leaflet-areaselect_example_.png…]()

I guess if it's the chrome's internal problem in DOMs' render strategy, because I didn't get the white line in firefox browser (52.0.1 (64-bit)). Here is the observation I found: In one areaselect instance, the three parts of your shades' height (top+left/right+bottom) equals to the map instance's height, but when the map instance height is 665.39px, the shades' total height is 664.98px. (193.99px + 193.99px + 277px), around 0.5px differences.

So I think it may not get a nice solution right now if the issue belonged to the problem caused by chrome internally. I would try to find some details about chrome and provide here, hope that can help you a little bit when you have some time to look back the issue in the future.

**Comment by hijiangtao** [comment]
It seems my network is very bad, so I can't upload the image right now. I will update it later (the appearance is the same as the first picture above).

**Comment by heyman** [comment]
I managed to reproduce it in Chrome on OSX now. I don't know what's causing it though.

**Comment by mdahamshi** [comment]
Hey
I had the same issue 
Please try to use `map.invalidateSize();` when changing the window size (or any map parent).
It worked for me.

**Comment by hijiangtao** [comment]
@mdahamshi Thanks for your tips, I'll try it later to see if it can fix my problem. :-)

**Comment by lweller** [comment]
I fixed this issue by calculating all shade geometries based the left top corner of hte map. Mixing top/bottom or left/right may produce some impresisions (probably due to internal rouding errors) in some browsers.
