### ISSUE TITLE
Lng is wrong in certain parts of the world

### ISSUE THREAD

**Issue by PaulDMendoza** [heyman/leaflet-areaselect#28]
With this map
![image](https://user-images.githubusercontent.com/1039795/30090332-695902a8-9267-11e7-825a-395c08ba47f5.png)

I get these bounds

![image](https://user-images.githubusercontent.com/1039795/30090327-5f7f035e-9267-11e7-966b-0a56a435a566.png)

**Comment by heyman** [comment]
Hmm, strange. We use Leaflet methods to convert pixel coordinates to lat/lng (https://github.com/heyman/leaflet-areaselect/blob/master/src/leaflet-areaselect.js#L34-L35).

Unfortunately I don't have the time to investigate this at the moment.

**Comment by valerio-bozzolan** [comment]
Hi @PaulDMendoza. I think this may be the cause of your problem:

https://stackoverflow.com/questions/18063278/leaflet-getbounds-returning-longitudes-greater-than-180

If yes, or if you cannot reproduce anymore, please mark as closed :) Thank you so much!
