### ISSUE TITLE
Releasing a version

### ISSUE THREAD

**Issue by savolkov** [heyman/leaflet-areaselect#31]
Hello!

We are using your plugin in our project, can you please release it so we (and actually other people) could make a reference to exact version of plugin.

Thanks a lot in advance!

p.s. update an example page, it's still not working ;)

**Comment by savolkov** [comment]
Hey, we still need it

**Comment by savolkov** [comment]
Hey...

**Comment by valerio-bozzolan** [comment]
I have no idea about that "Releasing a version" means, but probably we are talking about this thing:

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

So a `git tag` is needed first.
