### ISSUE TITLE
Angular problem

### ISSUE THREAD

**Issue by jegjessing** [heyman/leaflet-areaselect#36]
Hi

I cannot load the module using angular 7. I have several other leaflet plugins working, but this one just wont load.
Any idea why

**Comment by heyman** [comment]
Hi! There's a possibility that some version of Leaflet (probably 1.0) broke this plugin. I'm not using it on any active websites, so I haven't tested it. If that's the case, I'm guessing it's not very hard for someone to fix though.

**Comment by heyman** [comment]
The plugin should now work with the latest version of Leaflet again.
