### ISSUE TITLE
What's 'getBBoxCoordinates' for?

### ISSUE THREAD

**Issue by DoronovIV** [heyman/leaflet-areaselect#47]
Hey. I've used your tool in one of my projects and as a beginner I've gained a lot of experience from it. Thanks a lot.

In short, I'd like to know what `getBBoxCoordinates` function exists for :)
I haven't noticed it called in the js file, I suppose you would use it somewhere else.

**Comment by heyman** [comment]
It says in the Readme: "If you need the coordinates for all four corners of the bounding box" 😄

**Comment by heyman** [comment]
Sorry, you're right, the `getBBoxCoordinates` is redundant. It was quite awhile since I looked at this code, and I didn't realize `getBounds()` existed when I wrote my previous reply. I've now removed the getBBoxCoordinates (0c15fa6e0edb750588ee6b0c0dcefb32a342000f).
