### ISSUE TITLE
Firefox issue: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by asalisbury** [heyman/leaflet-areaselect#9]
Resize attempts in Firefox (I only tested versions 31.0 and 32.0.3) result in a seizing up of the map and areaselect box. It becomes largely unusable.

Leaflet logs an error to the console:
`Error: Invalid LatLng object: (NaN, NaN)`

I'll try additional versions and in different environments later.

**Comment by valerio-bozzolan** [comment]
Hi @asalisbury, if you think this was already fixed, please mark as closed :) Thank you so much!

**Comment by asalisbury** [comment]
No idea, as this was almost a decade ago. 😂
